source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "jekyll-theme-minimal"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
end

# Windows and JRuby does not include zoneinfo files
gem "tzinfo", ">= 1", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
