name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - name: Build site
        run: |
          bundle install
          bundle exec jekyll build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: _site
